# vim: ft=yaml.ansible
---
- name: Setup dotfiles and software
  hosts: all
  vars:
    install_software: false

  roles:
    - role: homebrew
      when: ansible_facts['os_family'] == 'Darwin'
    - role: git
    - role: bat
    - role: btop
    - role: neovim
    - role: shell
    - role: tmux

    # Setup Desktop environment
    - role: i3
      when: ansible_facts['os_family'] != 'Darwin'
    - role: rofi
      when: ansible_facts['os_family'] != 'Darwin'
    - role: wezterm
