---
- name: Setup CLI environment and associated tools
  hosts: all
  vars:
    install_software: false

  roles:
    - role: zsh
    - role: bash
      when: '"bash" in ansible_user_shell'

    - role: neovim
    - role: tmux
    - role: bat
    - role: git
