---
- name: Create the directory where ZSH's libs will live
  ansible.builtin.file:
    dest: ~/.local/share/shell
    state: directory
    mode: 0755

- name: Create the custom ZSH folder
  ansible.builtin.file:
    dest: ~/.local/share/shell/zsh_custom
    state: directory
    mode: 0755

- name: Create the custom ZSH plugin folder
  ansible.builtin.file:
    dest: ~/.local/share/shell/zsh_custom/plugins
    state: directory
    mode: 0755

- name: Create the custom ZSH themes folder
  ansible.builtin.file:
    dest: ~/.local/share/shell/zsh_custom/themes
    state: directory
    mode: 0755

- name: Install OhMyZSH!
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.local/share/shell/ohmyzsh

- name: Install ZSH Syntax Highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git 
    dest: ~/.local/share/shell/zsh_custom/plugins/zsh-syntax-highlighting

- name: Install Powerlevel10K
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git 
    dest: ~/.local/share/shell/zsh_custom/themes/powerlevel10k

- name: Copy over the ZSHRC file
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Copy over the configuration file over for Powerlevel10k
  ansible.builtin.copy:
    src: p10k_configuration
    dest: ~/.local/share/shell/p10k_configuration
    mode: 0644

