---
- name: Create the directory where ZSH's libs will live
  ansible.builtin.file:
    dest: ~/.local/share/shell
    state: directory
    mode: 0755

- name: Install Antidote
  ansible.builtin.git:
    repo: git@github.com:mattmc3/antidote.git
    dest: ~/.local/share/shell/antidote

- name: Copy over the ZSHRC file
  ansible.builtin.copy:
    src: zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Copy over the ZPROFILE file
  ansible.builtin.copy:
    src: zprofile
    dest: ~/.zprofile
    mode: 0644

- name: Copy the plugins file
  ansible.builtin.copy:
    src: zsh_plugins
    dest: ~/.local/share/shell/zsh_plugins
    mode: 0644

- name: Copy over the configuration file over for Powerlevel10k
  ansible.builtin.copy:
    src: p10k_configuration
    dest: ~/.local/share/shell/p10k_configuration
    mode: 0644

