# vim: ft=yaml.ansible
---
- name: Check if i3wm is installed
  ansible.builtin.command:
    cmd: i3 --version
  register: i3_exists
  changed_when: false
  ignore_errors: true

- name: Install i3wm
  ansible.builtin.package:
    name: i3
    state: present
  when: i3_exists.rc != 0 and use_sudo
  register: i3_installed

- name: Create i3 config directory
  ansible.builtin.file:
    path: ~/.config/i3
    state: directory
    mode: "0750"
  when: i3_exists.rc == 0 or i3_installed.changed

- name: Copy i3 configuration
  ansible.builtin.copy:
    src: i3config
    dest: ~/.config/i3/config
    mode: "0640"
  when: i3_exists.rc == 0 or i3_installed.changed

- name: Create i3blocks directory
  ansible.builtin.file:
    path: ~/.config/i3blocks
    state: directory
    mode: "0750"
  when: i3_exists.rc == 0 or i3_installed.changed

- name: Copy i3blocks configuration
  ansible.builtin.copy:
    src: i3blocks
    dest: ~/.config/i3blocks/config
    mode: "0640"
  when: i3_exists.rc == 0 or i3_installed.changed
