# vim: ft=yaml.ansible
---
- name: Check current taps
  ansible.builtin.command:
    cmd: brew tap
  changed_when: false
  register: brew_taps

- name: Check if koekeishiya/formulae tap is installed
  ansible.builtin.set_fact:
    tap_installed: "{{ 'koekeishiya/formulae' in brew_taps.stdout }}"
  changed_when: false

- name: Install koekeishiya/formulae tap
  ansible.builtin.command:
    cmd: brew tapkoekeishiya/formulae
  changed_when: not tap_installed
  when: not tap_installed

- name: Check if skhd is installed
  ansible.builtin.command:
    cmd: which skhd
  ignore_errors: true
  changed_when: false
  register: skhd_installed

- name: Install skhd
  ansible.builtin.command:
    cmd: brew install skhd
  register: skhd_brew
  changed_when: '"Installing" in skhd_brew.stdout'
  when: not skhd_installed.rc == 0

- name: Install skhd Service  # noqa: no-handler
  ansible.builtin.command:
    cmd: skhd --install-service
  register: skhd_service
  changed_when: skhd_service.rc == 0
  when: skhd_brew.changed

- name: Upgrade skhd  # noqa: package-latest
  ansible.builtin.homebrew:
    name: koekeishiya/formulae/skhd
    state: latest
  register: skhd_brew
  when: (skhd_installed.rc == 0) and not skhd_brew.changed

- name: Create skhd's configuration directory
  ansible.builtin.file:
    path: ~/.config/skhd
    state: directory
    mode: "0750"
  when: skhd_brew.changed or skhd_installed.rc == 0

- name: Copy skhd preferences
  ansible.builtin.copy:
    src: files/skhdrc
    dest: ~/.config/skhd/skhdrc
    mode: "0640"
  when: skhd_brew.changed or skhd_installed.rc == 0
  register: skhd_config

- name: Reload skhd configuration  # noqa: no-handler
  ansible.builtin.command:
    cmd: skhd --reload
  changed_when: skhd_config.changed
  when: skhd_config.changed and not skhd_brew.changed

- name: Toggle the skhd service  # noqa: no-handler
  ansible.builtin.command:
    cmd: skhd --stop-service; skhd --start-service
  changed_when: skhd_brew.changed
  when: skhd_brew.changed
