# vim: ft=yaml.ansible
---
- name: Check current taps
  ansible.builtin.command:
    cmd: brew tap
  changed_when: false
  register: brew_taps

- name: Check if FelixKratz/formulae tap is installed
  ansible.builtin.set_fact:
    tap_installed: "{{ 'felixkratz/formulae' in brew_taps.stdout }}"
  changed_when: false

- name: Install FelixKratz/formulae tap
  ansible.builtin.command:
    cmd: brew tap FelixKratz/formulae
  changed_when: not tap_installed
  when: not tap_installed

- name: Check if sketchybar is installed
  ansible.builtin.command:
    cmd: which sketchybar
  changed_when: false
  ignore_errors: true
  register: sketchybar_installed

- name: Install sketchybar
  ansible.builtin.command:
    cmd: brew install sketchybar
  register: sketchybar_brew
  changed_when: '"Installing" in sketchybar_brew.stdout'
  when: not sketchybar_installed.rc == 0

- name: Install lua (required for theme)
  ansible.builtin.command:
    cmd: brew install lua
  register: lua_brew
  changed_when: '"Pouring" in lua_brew.stdout'

- name: Install swtichaudio-osx (required for theme)
  ansible.builtin.command:
    cmd: brew install switchaudio-osx
  register: switchaudio_brew
  changed_when: '"Pouring" in switchaudio_brew.stdout'

- name: Install nowplaying-cli (required for theme)
  ansible.builtin.command:
    cmd: brew install nowplaying-cli
  register: lua_brew
  changed_when: '"Pouring" in lua_brew.stdout'

- name: Install sf-symbols (required for theme)
  ansible.builtin.command:
    cmd: brew install --cask sf-symbols
  register: lua_brew
  changed_when: '"Installing" in lua_brew.stdout'

- name: Install sketchybar Service  # noqa: no-handler
  ansible.builtin.command:
    cmd: sketchybar --install-service
  register: sketchybar_service
  changed_when: sketchybar_service.rc == 0
  when: sketchybar_brew.changed

- name: Upgrade sketchybar  # noqa: package-latest
  ansible.builtin.homebrew:
    name: sketchybar
    state: latest
  register: sketchybar_brew
  when: (sketchybar_installed.rc == 0) and not sketchybar_brew.changed

- name: Create sketchybar's configuration directory
  ansible.builtin.file:
    path: ~/.config/sketchybar
    state: directory
    mode: "0755"
  when: sketchybar_brew.changed or sketchybar_installed.rc == 0

- name: Copy the configuration for Sketchybar
  ansible.builtin.copy:
    src: sketchy/
    dest: ~/.config/sketchybar
    mode: "0644"
  register: sketchybar_config
  when: sketchybar_brew.changed or sketchybar_installed.rc == 0

- name: Reload sketchybar configuration  # noqa: no-handler
  ansible.builtin.command:
    cmd: sketchybar --reload
  changed_when: sketchybar_config.changed
  when: sketchybar_config.changed and not sketchybar_brew.changed

- name: Toggle the sketchybar service  # noqa: no-handler
  ansible.builtin.command:
    cmd: sketchybar --stop-service; sketchybar --start-service
  changed_when: sketchybar_brew.changed
  when: sketchybar_brew.changed
