# vim: ft=yaml.ansible
---
- name: Check if tmux is installed
  ansible.builtin.command:
    cmd: tmux -V
  register: tmux_exists
  changed_when: false
  ignore_errors: true

- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: present
  when: tmux_exists.rc != 0 and use_sudo
  register: tmux_installed

- name: Create tmux's configuration directory
  ansible.builtin.file:
    path: ~/.config/tmux
    mode: "0750"
    state: directory
  when: tmux_exists.rc == 0 or tmux_installed.changed

- name: Copy tmux's configuration file
  ansible.builtin.copy:
    src: tmux.conf
    dest: ~/.config/tmux/tmux.conf
    mode: "0640"
  when: tmux_exists.rc == 0 or tmux_installed.changed

- name: Link tmux configuration file for legacy support
  ansible.builtin.file:
    src: ~/.config/tmux/tmux.conf
    dest: ~/.tmux.conf
    state: link
  when: tmux_exists.rc == 0 or tmux_installed.changed

- name: Download the catpuccin theme  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/catppuccin/tmux.git
    dest: ~/.config/tmux/plugins/catppuccin/tmux
    version: v2.1.2
    force: true
  when: tmux_exists.rc == 0 or tmux_installed.changed
