#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Switch to zsh iff it's available, otherwise stay here.
if command -v zsh &> /dev/null
then
    export SHELL=$(which zsh)
    exec zsh -l
fi

# Because TMUX can break things too
if [[ $TERM == tmux-256color ]]; then
    if ! infocmp tmux-256color >/dev/null 2>&1; then
        export TERM='xterm-256color'
    fi
fi

echo "You're in bash, system does not have zsh installed."
if [[ -f "/etc/bashrc" ]]; then
    echo "Sourcing /etc/bashrc"
    source /etc/bashrc
fi
