# vim: ft=yaml.ansible
---
- name: Check if neovim is installed
  ansible.builtin.command:
    cmd: nvim --version
  register: neovim_exists
  changed_when: false
  ignore_errors: true

- name: Install Neovim
  ansible.builtin.package:
    name: neovim
    state: present
  when: neovim_exists.rc != 0 and use_sudo
  register: neovim_installed

- name: Create the Neovim configuration directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
    mode: "0750"
  when: neovim_exists.rc == 0 or neovim_installed.changed

- name: Copy the init file for Neovim
  ansible.builtin.copy:
    src: init.lua
    dest: ~/.config/nvim/init.lua
    mode: "0640"
  when: neovim_exists.rc == 0 or neovim_installed.changed

- name: Copy the configuration for Neovim
  ansible.builtin.copy:
    src: lua/
    dest: ~/.config/nvim/lua
    mode: "0640"
  when: neovim_exists.rc == 0 or neovim_installed.changed

- name: Remove old packer configuration
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/pack/packer
    state: absent
  when: neovim_exists.rc == 0 or neovim_installed.changed

- name: Check if vim is installed
  ansible.builtin.command:
    cmd: vim --version
  register: vim_exists
  changed_when: false
  ignore_errors: true

- name: Copy the default vim configuration
  ansible.builtin.copy:
    src: vimrc
    dest: ~/.vimrc
    mode: "0640"
  when: vim_exists.rc == 0

- name: Copy the default Intellij vim configuration
  ansible.builtin.copy:
    src: ideavimrc
    dest: ~/.ideavimrc
    mode: "0640"
