# vim: ft=yaml.ansible
---
- name: Check if bat is installed
  ansible.builtin.command:
    cmd: bat --version
  register: bat_exists
  changed_when: false
  ignore_errors: true

- name: Install bat
  ansible.builtin.package:
    name: bat
    state: present
  when: bat_exists.rc != 0 and install_software
  register: bat_installed

- name: Create the directory where bat's config lives
  ansible.builtin.file:
    dest: ~/.config/bat
    state: directory
    mode: "0755"
  when: bat_exists.rc == 0 or bat_installed.changed

- name: Install Catppuccin Themes  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/catppuccin/bat.git
    dest: ~/.config/bat/themes
    update: true
  register: bat_theme_installed
  when: bat_exists.rc == 0 or bat_installed.changed

- name: Copy over the bat config
  ansible.builtin.copy:
    src: config
    dest: ~/.config/bat/config
    mode: "0644"
  when: bat_exists.rc == 0 or bat_installed.changed

- name: Initialize bat's cache  # noqa: ignore-errors
  ansible.builtin.command:
    cmd: bat cache --build
  when: bat_exists.rc == 0 or bat_installed.changed
  changed_when: bat_theme_installed.changed
  ignore_errors: true
